XXXXXXX
XXXXXXXXXXXXXXXX X
  XXXXXX XXXX
  XXXXXXX XXX XXXXX XXXXX
  XXXXXXX XXXX XXXX XXXX XXXXX
  XXXXXXXXX XXXXXXXX
  XXXXXXXXXXX XXX XXX XXX XXXXXXXX
  XXXXXXXXX XXXXXXXXX
X

XX X
    XXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXX
    XXXX XXXXXX
    XXXXXX XXXXXX
X
XXXXXXXX
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXX XXXXXXXXXXX X
      XXXX XXXXXXXXXXXXXXXXXX XXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
            XX  XXXXXXXXX XXXXXXXX XXXXXX  XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXX
    XXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
      XXXX XXXXXX


    XXXXXX XXX
  XXXX XXXXXX XXX
XXXXXX
