# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-29 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('mobile', models.IntegerField(default=10)),
                ('coverletter', models.CharField(max_length=2000)),
                ('resume', models.FileField(null=True, upload_to=homepage.models.getAttachmentPath)),
            ],
        ),
        migrations.CreateModel(
            name='Apptips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('image1', models.ImageField(null=True, upload_to=homepage.models.getAImageAttachment)),
                ('size', models.IntegerField(choices=[(b'6', b'6'), (b'12', b'12')], default=b'6')),
                ('tipname', models.CharField(max_length=200, null=True)),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='homepage.Apptips')),
            ],
        ),
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('jobtype', models.CharField(choices=[(b'Intern', b'Intern'), (b'Contract', b'Contract'), (b'Fulltime', b'Fulltime')], default=b'Char', max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('maxctc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(null=True)),
                ('attachment', models.FileField(null=True, upload_to=homepage.models.getERPPictureUploadPath)),
                ('mediaType', models.CharField(choices=[(b'onlineVideo', b'onlineVideo'), (b'video', b'video'), (b'image', b'image'), (b'onlineImage', b'onlineImage'), (b'doc', b'doc')], default=b'image', max_length=20)),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceDocsUploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdfDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to=homepage.models.getPdfImageAttachment)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('itemNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'Boolean', b'Boolean'), (b'Char', b'Char'), (b'float', b'float'), (b'Integer', b'Integer')], default=b'Char', max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('inPdf', models.BooleanField(default=True)),
                ('inUI', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent_name', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('rteData1_en', models.TextField(max_length=5000, null=True)),
                ('rteData1_otl', models.TextField(max_length=5000, null=True)),
                ('rteData2_en', models.TextField(max_length=5000, null=True)),
                ('rteData2_otl', models.TextField(max_length=5000, null=True)),
                ('defaultImage', models.ImageField(null=True, upload_to=homepage.models.getOGImageAttachment)),
                ('backgroundImage1', models.ImageField(null=True, upload_to=homepage.models.getBGImageAttachment)),
                ('backgroundImage2', models.ImageField(null=True, upload_to=homepage.models.getBGImageAttachment)),
                ('productImage1', models.ImageField(null=True, upload_to=homepage.models.getPImageAttachment)),
                ('productImage2', models.ImageField(null=True, upload_to=homepage.models.getPImageAttachment)),
                ('pdfgenerated', models.BooleanField(default=False)),
                ('disclaimer_en', models.TextField(null=True)),
                ('disclaimer_otl', models.TextField(null=True)),
                ('keyword1', models.TextField(null=True)),
                ('keyword2', models.TextField(null=True)),
                ('keyword3', models.TextField(null=True)),
                ('keyword4', models.TextField(null=True)),
                ('productfields', models.TextField(null=True)),
                ('media', models.ManyToManyField(related_name='templateMedia', to='homepage.Media')),
            ],
        ),
        migrations.CreateModel(
            name='ProductValueMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bool', models.BooleanField(default=True)),
                ('char', models.CharField(max_length=200)),
                ('fValue', models.FloatField(default=0)),
                ('iValue', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productFields', to='homepage.ProductField')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='homepage.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dated', models.DateField()),
                ('slot', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30, null=True)),
                ('emailId', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='productfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTemplates', to='homepage.ProductTemplate'),
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productValueTemplates', to='homepage.ProductTemplate'),
        ),
        migrations.AddField(
            model_name='apply',
            name='forg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CareerField', to='homepage.CareerField'),
        ),
    ]
