# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_accessories_accessoriessection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='sectionImage',
        ),
    ]
