# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_accessories_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='categoryName',
            field=models.CharField(default=b'ab', max_length=200),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='image1',
            field=models.ImageField(null=True, upload_to=homepage.models.getaccessImageAttachment),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='image2',
            field=models.ImageField(null=True, upload_to=homepage.models.getaccessImageAttachment),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='productName',
            field=models.CharField(default=b'ab', max_length=200),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='tagLine',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
