# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190703_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='bottomtext',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
