# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_accessoriessection_bottomtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='basicProductName',
            field=models.CharField(default=b'abc', max_length=200),
        ),
    ]
