# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190703_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('itemNumber', models.IntegerField(default=0)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessoriessectionValue', to='homepage.AccessoriesSection')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'Boolean', b'Boolean'), (b'Char', b'Char'), (b'float', b'float'), (b'Integer', b'Integer')], default=b'Char', max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('inPdf', models.BooleanField(default=True)),
                ('inUI', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoriessectionData', to='homepage.AccessoriesSection')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesValueMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bool', models.BooleanField(default=True)),
                ('char', models.CharField(max_length=200)),
                ('fValue', models.FloatField(default=0)),
                ('iValue', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoriesField', to='homepage.AccessoriesField')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoriesData', to='homepage.AccessoriesData')),
            ],
        ),
    ]
