# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190704_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesdata',
            name='productBaseName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accessoriesfield',
            name='productBaseName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accessoriesvaluemap',
            name='productBaseName',
            field=models.CharField(max_length=200),
        ),
    ]
