# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190704_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptips',
            name='lang',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
