# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_apptips_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to=homepage.models.albumImageAttachment)),
            ],
        ),
    ]
