# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_albumimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptips',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
