# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20190705_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptips',
            name='text',
            field=models.TextField(max_length=40000, null=True),
        ),
    ]
