# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20190719_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='backgroundImage1',
            field=models.ImageField(null=True, upload_to=homepage.models.getaccessImageAttachment),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='backgroundImage2',
            field=models.ImageField(null=True, upload_to=homepage.models.getaccessImageAttachment),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
