# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-14 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20190814_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='catalogBG1',
            field=models.ImageField(null=True, upload_to=homepage.models.getPImageAttachment),
        ),
        migrations.AddField(
            model_name='accessoriessection',
            name='catalogBG2',
            field=models.ImageField(null=True, upload_to=homepage.models.getPImageAttachment),
        ),
    ]
