# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20190814_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='des_ch',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='des_de',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='disclaimer_ch',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='rteData1_ch',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='rteData2_ch',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='rteDescription_ch',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='rteDescription_de',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
