# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20190814_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptips',
            name='image1',
            field=models.FileField(null=True, upload_to=homepage.models.getAImageAttachment),
        ),
    ]
