# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_apptips_mediatyp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptips',
            name='mediaTyp',
            field=models.CharField(default=b'image', max_length=200, null=True),
        ),
    ]
