# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20190821_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptips',
            name='mediaTyp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
