# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20190821_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriessection',
            name='media',
            field=models.ManyToManyField(related_name='accessoriesMedia', to='homepage.Media'),
        ),
    ]
