# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_locations_representation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='lng',
        ),
        migrations.AddField(
            model_name='locations',
            name='address_de',
            field=models.TextField(max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='address_en',
            field=models.TextField(max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='address_zh',
            field=models.TextField(max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
