# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_auto_20190905_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='long',
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
