# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_auto_20190905_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='lng',
            new_name='long',
        ),
    ]
