# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_auto_20190905_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
