BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Connected Accounts') BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBB

BB BBBBBBBBBBBBB
XXX gettext(u'You can sign in to your account using any of the following third party accounts:') SSS SSS SSSS SS SS SSSS SSSSSSS SSSSS SSS SS SSS SSSSSSSSS SSSSS SSSSS SSSSSSSSSXXXX


XXXXX XXXXXXXXXXXXXX
BBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
             
        BBBBBB
    XXXXXX
BBBBB


XXXXXX XXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXX
	 gettext(u'Provider') 
      XXXXX
      XXXX
	 gettext(u'Account') 
      XXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
    XXXX
      XXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXX
XXXXXXXX
      XXXXX
      XXXX
	
      XXXXX
    XXXXX
BBBBBBB
BBBBBB
  XXXXXXXX
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
XXXXXX

XXXXXXXXXXX

XXXXXXX

BBBB
XXXX XXXXXXXXXXXXXX
XXXXXXXX gettext(u'None!') XXXXXXXXX  gettext(u'You currently have no social network accounts connected to this account.') 
XXXXXX
BBBBB

XXXX gettext(u'Add a 3rd Party Account') XXXXX

XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB
XXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB


