BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Signup') BBBBBBBB

BBBBB BBBBBBB
    XXXX gettext(u'Sign Up') XXXXX

XXX gettext(u'You are about to use your %(provider_name)s account to login to\n%(site_name)s. As a final step, please complete the following form:') SSS SSS SSSSS SS SSS SSSS SSSSSSSSSSSSSSSSS SSSSSSS SS SSSSS SS
SSSSSSSSSSSSSS SS S SSSSS SSSSS SSSSSS SSSSSSSS SSS SSSSSSSSS SSSSSXXXX

XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
  BBBBBBBBBB
  
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXX gettext(u'Sign Up') XXXXXXXXX
  XXXXXX
XXXXXXX


BBBBBBBB
