BBBB BBBB
BBBB BBBBBBB

BBBBBBBBBBBB BBBB BB BBBBBBBBBBBB
XXXXXXXXXXX gettext(u'Note') XXXXXXXXXX  gettext(u'you are already logged in as %(user_display)s.') SSS SSS SSSSSSS SSSSSS SS SS SSSSSSSSSSSSSSSSSXXXX
