BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Confirm E-mail Address') BBBBBBBB


BBBBB BBBBBBB

XXXX gettext(u'Confirm E-mail Address') XXXXX

BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
        
XXX gettext(u'You have confirmed that <a href="mailto:%(email)s">%(email)s</a> is an e-mail address for user %(user_display)s.') SSS SSSS SSSSSSSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SS SSSSSS SSSSSSS SSS SSSS SSSSSSSSSSSSSSSSSXXXX

BBBBBBBB
