BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Account') BBBBBBBB

BBBBB BBBBBBB
    XXXX gettext(u'E-mail Addresses') XXXXX
BB BBBBBBBBBBBBBBBBBBBBBBBBB
XXX gettext(u'The following e-mail addresses are associated with your account:') XXXX

XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX

      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXX


    BB BBBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXX gettext(u'Verified') XXXXXXX
    BBBB
    XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Unverified') XXXXXXX
    BBBBB
      BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX gettext(u'Primary') XXXXXXXBBBBB
XXXXXXXX
XXXXXX
  BBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X gettext(u'Make Primary') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X gettext(u'Re-send Verification') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X gettext(u'Remove') XXXXXXXXX
XXXXXX

XXXXXXXXXXX
XXXXXXX

BBBB
XXXXXXXXXXX gettext(u'Warning:') XXXXXXXXX  gettext(u'You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc.') XXXX

BBBBB


    XXXX gettext(u'Add E-mail Address') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Add E-mail') XXXXXXXXX
    XXXXXXX

BBBBBBBB


BBBBB BBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXX X
  XXX XXXXXXX X X gettext(u'Do you really want to remove the selected e-mail address?') XX
  XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XX XX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
      X
    XXX
  X
XXXXX
XXXXXXXXX
BBBBBBBB
