BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBB
BBBB BBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Sign In') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX gettext(u'Sign In') XXXXX

	BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB

	BB BBBBBBBBBBBBBBBBBBBBBBB
	XXX gettext(u'Please sign in with one\n\tof your existing third party accounts. Or, <a href="/register">sign up</a>\n\tfor a %(site_name)s account and sign in below:') SSSSSS SSSS SS SSSS SSS
	SS SSSS SSSSSSSS SSSSS SSSSS SSSSSSSSS SSS SS SSSSSSSSSSSSSSSSSSSSS SSSSSS
	SSS S SSSSSSSSSSSSS SSSSSSS SSS SSSS SS SSSSSSXXXX

	XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

	  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB
	  XXXXX

	  XXXX XXXXXXXXXXXXXXXXX gettext(u'or') XXXXXX

	XXXXXX

	BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

	BBBB
	XXX gettext(u'If you have not created an account yet, then please\n\t<a href="%(signup_url)s">sign up</a> first.') SS SSS SSSS SSS SSSSSSS SS SSSSSSS SSSS SSSS SSSSSS
	SS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS SSSSSSXXXX
	BBBBB

	XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
	  BBBBBBBBBB
	   FFFFFFFFF
	  BB BBBBBBBBBBBBBBBBBBBB
	  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
	  BBBBB
	  XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot Password?') XXXX
	  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sign In') XXXXXXXXX
	XXXXXXX
XXXXXX
BBBBBBBB
