BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Sign Out') BBBBBBBB

BBBBB BBBBBBB
XXXX gettext(u'Sign Out') XXXXX

XXX gettext(u'Are you sure you want to sign out?') XXXX

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
  BBBBB
  XXXXXXX XXXXXXXXXXXXXX gettext(u'Sign Out') XXXXXXXXX
XXXXXXX


BBBBBBBB
