BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXBB BBBBBBBBBB gettext(u'Bad Token') BBBB gettext(u'Change Password') BBBBBXXXXX

		BB BBBBBBBBBB
			BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
			XXX gettext(u'The password reset link was invalid, possibly because it has already been used.  Please request a <a href="%(passwd_reset_url)s">new password reset</a>.') SSS SSSSSSSS SSSSS SSSS SSS SSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSSSS SSSS SSSSS  SSSSSS SSSSSSS S SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSXXXX
		BBBB
			BB BBBB
				XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
					BBBBBBBBBB
					 FFFFFFFFF
					XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'change password') XXX
				XXXXXXX
			BBBB
				XXX gettext(u'Your password is now changed.') XXXX
			BBBBB
		BBBBB
	XXXXXX
BBBBBBBB
