BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Change Password') BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX gettext(u'Change Password') XXXXX

		XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBBBBB
			 FFFFFFFFF
			XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Change Password') XXXXXXXXX
		XXXXXXX
	XXXXXX
    
BBBBBBBB
