BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Set Password') BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX gettext(u'Set Password') XXXXX

		XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
			BBBBBBBBBB
			 FFFFFFFFF
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Set Password') XXX
		XXXXXXX
	XXXXXX
BBBBBBBB
