BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBB
BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Password Reset') BBBBBBBB

BBBBB BBBBBBB
	XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XXXX gettext(u'Password Reset') XXXXX
		BB BBBBBBBBBBBBBBBBBBBBB
		BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
		BBBBB

		XXX gettext(u"Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.") XXXX

		XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
			BBBBBBBBBB
			 FFFFFFFFF
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'Reset My Password') X XX
		XXXXXXX

		XXX gettext(u'Please contact us if you have any trouble resetting your password.') SSSSSS SSSSSSS SS SS SSS SSSS SSS SSSSSSS SSSSSSSSS SSSS SSSSSSSSSXXXX
	XXXXXX
BBBBBBBB
