XXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXX  FFFFFFF F FFFFFFFFFFFFFFF F FFX X
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX FFFFFX  XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFXXXXXXX  FFFFFFFFFFFFFXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX FFFFFFF XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX FFFFFFFFFF
      XXXXXX
    XXXXXX
  XXXXXX
XXXXX
