BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBBB

BBBBB BBBBBBBBBB gettext(u'Password Reset') BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX gettext(u'Password Reset') XXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB

    XXX gettext(u"Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.") XXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXX X
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Reset My Password') X XX
        XXXXXX
      XXXXXXX
    XXX gettext(u'Please contact us if you have any trouble resetting your password.') SSSSSS SSSSSSS SS SS SSS SSSS SSS SSSSSSS SSSSSSSSS SSSS SSSSSSSSSXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
BBBBBBBB
